In [3]:
import pandas as pd
import numpy as np

##### 1. Write a Pandas program to change the order of index of a given series.

In [2]:
s=pd.Series(data=[5,6,7,8],index=['a','s','d','f'])
print(s)
s=s.reindex(index=['f','d','s','a'])
print(s)

a    5
s    6
d    7
f    8
dtype: int64
f    8
d    7
s    6
a    5
dtype: int64


#### 2. Write a Python program to add, subtract, multiple and divide two Pandas Series.

In [5]:
s1=pd.Series([2,4,6,8,10])
s2=pd.Series([1,3,5,7,9])
add=s1+s2
sub=s1-s2
mul=s1*s2
div=s1/s2
print(add)
print(sub)
print(mul)
print(div)

0     3
1     7
2    11
3    15
4    19
dtype: int64
0    1
1    1
2    1
3    1
4    1
dtype: int64
0     2
1    12
2    30
3    56
4    90
dtype: int64
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


#### 3. Write a Python program to convert a Panda module Series to Python list and it's type

In [6]:
ser=pd.Series(['a','b','c','d'])
print(type(ser))
lis=ser.tolist()
print(lis)
print(type(lis))


<class 'pandas.core.series.Series'>
['a', 'b', 'c', 'd']
<class 'list'>


#### 4. Write a Pandas program to select the rows where the score is missing, i.e. is NaN

 - Sample Python dictionary data and list labels:

 - exam_data = {name: [Sachin,Ganguly,Kohli,Johnson,Taylor,Waugh,Yuvraj,Kambli,Srinath,Munaf],
    score: [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    attempts: [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    qualify: [yes,no,yes,no,no,yes,yes,no,no,yes]}
    labels = [a,b,c,d,e,f,g,h,i,j]

In [9]:
name=['Sachin','Ganguly','Kohli','Johnson','Tylor','Waugh','Yuvraj','Kambil','Srinath','Munaf']
score=[12.5,9,16.5,np.nan,9,20,14.5,np.nan,8,19]
attempts=[1,3,2,3,2,3,1,1,2,1]
qualify=['yes','no','yes','no','no','yes','yes','no','no','yes']
labels=['a','b','c','d','e','f','g','h','i','j']
df={'score':score,'attempts':attempts,'qualify':qualify,'labels':labels}
exam_data=pd.DataFrame(df,index=name)
print(exam_data[exam_data['score'].isnull()])

         score  attempts qualify labels
Johnson    NaN         3      no      d
Kambil     NaN         1      no      h


#### 5. Write a Pandas program to create todays date

In [11]:
print(pd.datetime.now().date())

2019-12-31


#### 6.Write a Pandas program to create a Pivot table, by considering Titanic Dataset

In [14]:
df=pd.read_csv('titanic.csv')
result=pd.pivot_table(df,index=['Sex','Age'],aggfunc=np.sum)
print(result)

                  Fare  Parch  PassengerId  Pclass  SibSp  Survived
Sex    Age                                                         
female 0.75    38.5166      2         1115       6      4         2
       1.00    26.8750      3          555       6      1         2
       2.00   259.4750      9         2278      15      9         2
       3.00    62.6542      3          419       5      4         1
       4.00   114.1417      6         2258      13      4         5
...                ...    ...          ...     ...    ...       ...
male   70.00   81.5000      1         1419       3      1         0
       70.50    7.7500      0          117       3      0         0
       71.00   84.1584      0          591       2      0         0
       74.00    7.7750      0          852       3      0         0
       80.00   30.0000      0          631       1      0         1

[145 rows x 6 columns]


#### 7.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10

In [12]:
np.arange(2,11).reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

#### 8.Illustrate the difference between ravel and flatten by taking considering multidimensional array.

In [17]:
q=np.arange(1,10).reshape(3,3)
print(q.flatten())
print(q.ravel())

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


#### 9. Create a 3×3 numpy array, find out the Minimum,Maximum values and also their indices accordingly for each axes. Also find out the Statistical methods such as Standard Deviation,Cumulative sum and product.

In [16]:
r=np.random.random((3,3))
print(r)
print(np.min(r))
print(np.max(r))
print(np.std(r))
print(np.min(r))

[[0.78517473 0.3123832  0.02394632]
 [0.57900218 0.27928191 0.53877864]
 [0.44908786 0.01828028 0.44991347]]
0.018280279814493205
0.7851747329705784
0.238267764271836
0.018280279814493205


#### 10. Illustrate the concept of splitting by taking random positive values and also implementing different stacking methods on them.

In [20]:
w=np.random.random((3,3))
r=np.random.random((3,3))
print(np.vstack((w,r)))
print(np.hstack((w,r)))

[[0.9067083  0.82033811 0.53705689]
 [0.95459047 0.80493765 0.80574931]
 [0.82211387 0.73890233 0.88419215]
 [0.79420545 0.55322592 0.63190836]
 [0.65989929 0.228528   0.42801632]
 [0.14180041 0.94117766 0.23561338]]
[[0.9067083  0.82033811 0.53705689 0.79420545 0.55322592 0.63190836]
 [0.95459047 0.80493765 0.80574931 0.65989929 0.228528   0.42801632]
 [0.82211387 0.73890233 0.88419215 0.14180041 0.94117766 0.23561338]]
