## Numpy

In [1]:
import numpy as ny

In [2]:
ar=ny.array([1,2,3,4])

In [3]:
ar1=ny.array([1,4,5,6.8])
ar1

array([1. , 4. , 5. , 6.8])

In [4]:
from numpy import array as ar

In [5]:
ar([1,5,7,3,3,33,5])

array([ 1,  5,  7,  3,  3, 33,  5])

In [6]:
ny.arange(50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [7]:
ar3=ny.arange(5,40,5)
ar3

array([ 5, 10, 15, 20, 25, 30, 35])

In [8]:
len(ar3)

7

In [9]:
ar3.shape

(7,)

In [10]:
ar4=ny.arange(1,10)
ar4

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
ar4.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
ar4.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
s=ny.ones(10)

In [18]:
s

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
s=ny.zeros(5)
s

array([0., 0., 0., 0., 0.])

In [20]:
s.astype(int)

array([0, 0, 0, 0, 0])

In [21]:
ar5=ny.arange(1,10)
ar5

array([1, 2, 3, 4, 5, 6, 7, 8, 9])